api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
    IngredientListView,
    api_follow_detail,
    api_favourite_detail,
    api_purchase_detail,
)

router = DefaultRouter()
router.register(r"ingredients", IngredientListView)

urlpatterns = [
    path("subscriptions/<author_id>", api_follow_detail),
    path("favourites/<recipe_id>", api_favourite_detail),
    path("purchases/<recipe_id>", api_purchase_detail),
]

urlpatterns += router.urls

foodgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("django.contrib.flatpages.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("api/v1/", include("api.urls")),
    path("", include("receipe.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

receipe/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("add/recipe", views.add_recipe, name="add_recipe"),
    path("follow", views.follow_index, name="follow"),
    path("favourite", views.favourite_index, name="favourite"),
    path("purchase", views.purchase_list, name="purchase"),
    path("products", views.upload, name="get_products"),
    path("<username>", views.profile, name="profile"),
    path("<username>/<recipe_id>", views.recipe_view, name="recipe_view"),
    path("<username>/<recipe_id>/edit", views.recipe_edit, name="recipe_edit"),
    path("<username>/<recipe_id>/delete", views.recipe_delete, name="recipe_delete"),
]

receipe/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Ingredients(models.Model):
    title = models.CharField(max_length=80)
    dimension = models.CharField(max_length=10)

    def __str__(self):
        return "%s %s" % (self.title, self.dimension)


class IngredientsRecipe(models.Model):
    ingredient = models.ForeignKey("Ingredients", on_delete=models.CASCADE, related_name="ingredient")
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, related_name="recipe", null=True, blank=True)
    amount = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.ingredient.title} {self.amount} {self.ingredient.dimension}'


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recipes")
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to="recipe/")
    descriptions = models.TextField()
    ingredient_list = models.ManyToManyField("Ingredients", related_name="recipes", through="IngredientsRecipe")
    cooking_time = models.PositiveIntegerField()

    breakfast = models.BooleanField(default=False, verbose_name="Завтрак")
    lunch = models.BooleanField(default=False, verbose_name="Обед")
    dinner = models.BooleanField(default=False, verbose_name="Ужин")


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")

    class Meta:
        unique_together = ['user', 'author']


class Favourite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_favourite")
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, related_name="recipe_favourite")


class Purchase(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer")
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, related_name="pur_recipe")

receipe/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "title",
            "breakfast",
            "lunch",
            "dinner",
            "cooking_time",
            "descriptions",
            "image",
        ]
        widgets = {
            "tag": forms.CheckboxSelectMultiple(),
        }

receipe/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponse

from .models import (
    Recipe,
    Ingredients,
    IngredientsRecipe,
    User,
    Follow,
    Purchase,
)
from .forms import RecipeForm
from .utils import get_ingredients, food_time_filter


def index(request):
    recipe = Recipe.objects.select_related(
        "author"
    ).order_by("-pub_date").all()
    recipe_list, food_time = food_time_filter(request, recipe)
    paginator = Paginator(recipe_list, 3)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(
        request, "index.html", {
            "page": page,
            "paginator": paginator,
            "food_time": food_time,
        }
    )


@login_required
def add_recipe(request):
    user = User.objects.get(username=request.user)
    if request.method == "POST":
        ingr = get_ingredients(request)
        form = RecipeForm(request.POST or None, files=request.FILES or None)
        if not ingr:
            form.add_error(None, 'Добавьте ингредиенты')

        elif form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = user
            recipe.save()
            for ingr_name, amount in ingr.items():
                ingr_obj = get_object_or_404(Ingredients, title=ingr_name)
                ingr_recipe = IngredientsRecipe(
                    ingredient=ingr_obj,
                    recipe=recipe,
                    amount=amount,
                )
                ingr_recipe.save()
            form.save_m2m()
            return redirect("index")

    else:
        form = RecipeForm()
    return render(request, "recipeform.html", {
        "form": form,
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    recipe = Recipe.objects.select_related("author").filter(author=author)
    recipe_list, food_time = food_time_filter(request, recipe)
    recipe_list = recipe_list.order_by("-pub_date")
    paginator = Paginator(recipe_list, 3)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(request, "profile.html", {
        "author": author,
        "page": page,
        "paginator": paginator,
        "food_time": food_time,
    })


def recipe_view(request, username, recipe_id):
    author = get_object_or_404(User, username=username)
    recipe = get_object_or_404(Recipe, pk=recipe_id, author=author)
    ingredients = IngredientsRecipe.objects.filter(recipe=recipe)
    return render(request, "single_recipe.html", {
        "recipe": recipe,
        "username": author,
        "ingredients": ingredients,
    })


@login_required
def recipe_edit(request, username, recipe_id):
    change = True
    profile = get_object_or_404(User, username=username)
    recipe = get_object_or_404(Recipe, pk=recipe_id, author=profile)
    ingr_objects = IngredientsRecipe.objects.filter(recipe=recipe)

    if request.method == "POST":
        ingr = get_ingredients(request)
        form = RecipeForm(
            request.POST or None,
            files=request.FILES or None,
            instance=recipe,
        )

        if not ingr_objects:
            form.add_error(None, "Добавьте ингредиенты!")

        elif form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = profile
            recipe.save()
            IngredientsRecipe.objects.filter(recipe=recipe).delete()

            for ingr_name, amount in ingr.items():
                ingr_obj = get_object_or_404(Ingredients, title=ingr_name)
                ingr_recipe = IngredientsRecipe(
                    ingredient=ingr_obj,
                    recipe=recipe,
                    amount=amount,
                )
                ingr_recipe.save()
            form.save_m2m()
            return redirect("index")

    else:
        form = RecipeForm(instance=recipe)
    return render(request, "recipeform.html", {
        "form": form,
        "recipe": recipe,
        "ingr": ingr_objects,
        "change": change,
    })


@login_required
def recipe_delete(request, username, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    user = request.user

    if request.method == "POST":
        author = get_object_or_404(User, username=username)
        if recipe.author == author == user or user.is_superuser:
            recipe.delete()
        return redirect("index")
    else:
        return render(request, "delete_submit.html", {
            "recipe_id": recipe_id,
            "username": username,
            "recipe": recipe,
        })


@login_required
def follow_index(request):
    follow = Follow.objects.filter(user=request.user)
    cnt = {}
    for author in follow:
        amount = Recipe.objects.filter(author=author.author).count()
        cnt[author.author] = amount
    paginator = Paginator(follow, 3)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(request, "follow.html", {
            "page": page,
            "paginator": paginator,
            "cnt": cnt,
        }
    )


@login_required
def favourite_index(request):
    recipe = Recipe.objects.select_related("author").filter(
        recipe_favourite__user__pk=request.user.id)
    recipes, food_time = food_time_filter(request, recipe)
    paginator = Paginator(recipes, 3)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(request, "favourite.html", {
            "page": page,
            "paginator": paginator,
            "food_time": food_time,
        }
    )


@login_required
def purchase_list(request):
    recipes = Purchase.objects.filter(buyer=request.user)
    return render(request, "shop_list.html", {
        "recipes": recipes,
    })


@login_required
def upload(request):
    recipes = Recipe.objects.filter(pur_recipe__buyer=request.user)
    ingredients = recipes.values(
        "ingredient_list__title",
        "ingredient_list__dimension",
    ).annotate(
        total_amount=Sum("recipe__amount")
    )
    file_data = ""

    for i in ingredients:
        line = " ".join(str(value) for value in i.values())
        file_data += line + "\n"

    response = HttpResponse(
        file_data,
        content_type="application/text charset=utf-8",
    )
    response["Content-Disposition"] = "attachment; filename='products.txt'"
    return response

receipe/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Заголовок страницы {% endblock %} | Продуктовый помощник </title>
    {% block static %}
    {% endblock %}
</head>
<body class="body">

{% block nav %}
{% endblock %}

<main class="main container">
    {% block content %}         
            <!-- Содержимое страницы -->
    {% endblock content %}    
</main>

{% include "footer.html" %}
</body>
</html>

receipe/templates/delete_submit.html
{% extends "base.html" %}
{% load static %}
{% block title %}Удаление рецепта{% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static '/pages/index.css' %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" %}
{% endblock %}
{% block content %}
    <div class="custom-center-block">
        <p class="custom-text-block">Удалить рецепт {{ recipe.title }}?</p>
        <div class="custom-button-block">
            <form method="POST" action="{% url 'recipe_delete' username recipe_id %}">
                {% csrf_token %}
                <button class="button button_style_blue">Удалить</button>
            </form>
            <form action="{% url 'recipe_view' username recipe_id %}" >
                <button class="button button_style_light-blue">Отмена</button>
            </form>
        </div>
    </div>
{% endblock %}

receipe/templates/favourite.html
{% extends "base.html" %}
{% load static %}
{% block title %}Избранное{% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static '/pages/index.css' %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" with favourite=True %}
{% endblock %}
{% block content %}
        {% csrf_token %}
        <div class="main__header">
            <h1 class="main__title">Избранное</h1>
            {% include "tags.html" with url=request.path food_time=food_time %}

        </div>
        <div class="card-list">
            {% for recipe in page %}
                {% include "recipe_item.html" with recipe=recipe %}
            {% endfor %}
        </div>
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}
<script src="{% static '/js/components/MainCards.js' %}"></script>

<script src="{% static '/js/components/Purchases.js' %}"></script>
<script src="{% static '/js/components/Favorites.js' %}"></script>

<script src="{% static '/js/config/config.js' %}"></script>
<script src="{% static '/js/components/CardList.js' %}"></script>
<script src="{% static '/js/components/Header.js' %}"></script>

<script src="{% static '/js/api/Api.js' %}"></script>
<script src="{% static 'favorite.js' %}"></script>
{% endblock %}

receipe/templates/follow.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Мои подписки{% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static '/pages/myFollow.css' %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" with follow=True %}
{% endblock %}
{% block content %}
    {% csrf_token %}
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    {% for follow in page %}
    <div class="card-list">
        <div class="card-user" data-author="{{ follow.author.pk }}">
        <div class="card-user__header">
            <h2 class="card-user__title">{{ follow.author.first_name }}</h2>
        </div>
        <div class="card-user__body">
            <ul class="card-user__items">
                {% for recipe in follow.author|get_recipes %}
                <li class="card-user__item">
                    <div class="recipe">
                        {% thumbnail recipe.image "250x250" crop="center" upscale=True as im %}
                        <img src="{{ im.url }}" alt="какой-то-текст" class="recipe__image">
                        {% endthumbnail %}
                        <h3 class="recipe__title"><a href="{% url 'recipe_view' recipe.author.username recipe.pk %}">{{ recipe.title }}</a></h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                    </div>
                </li>
                {% endfor %}
                {% if follow.author|get_count_recipes %}
                <li class="card-user__item">
                    <a href="{% url 'profile' follow.author %}" class="card-user__link link">{{ follow.author|get_count_recipes }}</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="card-user__footer">
            <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
        </div>
    </div>
    {% endfor %}
{% if page.has_other_pages %}
    {% include "paginator.html" with items=page paginator=paginator%}
{% endif %}
<script src="{% static '/js/config/config.js' %}"></script>
<script src="{% static '/js/components/MainCards.js' %}"></script>
<script src="{% static '/js/components/MyFollow.js' %}"></script>
<script src="{% static '/js/components/Subscribe.js' %}"></script>
<script src="{% static '/js/components/Header.js' %}"></script>
<script src="{% static '/js/api/Api.js' %}"></script>
<script src="{% static 'myFollow.js' %}"></script>
{% endblock %}

receipe/templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="/about/about-author/" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="/about/about-spec/" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

receipe/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Рецепты{% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static '/pages/index.css' %}">
{% endblock %}
{% block nav %}
    {% include 'nav.html' with index=True %}
{% endblock %}
{% block content %}
        <div class="main__header">
            {% csrf_token %}
            <h1 class="main__title">Рецепты</h1>
            {% include "tags.html" with url=request.path food_time=food_time %}
        </div>
        <div class="card-list">
            {% for recipe in page %}
                {% include "recipe_item.html" with recipe=recipe %}
            {% endfor %}
        </div>
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}
<script src="{% static '/js/components/MainCards.js' %}"></script>

<script src="{% static '/js/components/Purchases.js' %}"></script>
<script src="{% static '/js/components/Favorites.js' %}"></script>

<script src="{% static '/js/config/config.js' %}"></script>
<script src="{% static '/js/components/CardList.js' %}"></script>
<script src="{% static '/js/components/Header.js' %}"></script>

<script src="{% static '/js/api/Api.js' %}"></script>
<script src="{% static 'indexAuth.js' %}"></script>
{% endblock %}

receipe/templates/nav.html
<nav class="nav">
    <div class="nav__container container">
        <ul class="nav__items list">
            <li class="nav__item {% if index %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
            {% if user.is_authenticated %}
            <li class="nav__item {% if follow %}nav__item_active{% endif %}"><a href="{% url 'follow' %}" class="nav__link link">Мои подписки</a></li>
            <li class="nav__item {% if add_recipe %}nav__item_active{% endif %}"><a href="{% url 'add_recipe' %}" class="nav__link link">Создать рецепт</a></li>
            <li class="nav__item {% if favourite %}nav__item_active{% endif %}"><a href="{% url 'favourite' %}" class="nav__link link">Избранное</a></li>
            <li class="nav__item {% if purchase %}nav__item_active{% endif %}"><a href="{% url 'purchase' %}" class="nav__link link">Список покупок <span class="badge badge_style_blue nav__badge" id="counter">{{ user.buyer.count }}</span></a></li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
            <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
        </ul>
        {% else %}
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
            <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
        </ul>
        {% endif %}
    </div>
</nav>

receipe/templates/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if items.has_previous %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.previous_page_number }}"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
                {% if items.number == i %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="?page={{ i }}">{{ i }}</a></li>
                {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
        {% endfor %}
        {% if items.has_next %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.next_page_number }}"><span class="icon-right"></span></a></li>
        {% endif %}
    </ul>
</nav>

receipe/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %}{{ author.username }}{% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static '/pages/index.css' %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" with index=True %}
{% endblock %}
{% block content %}
        {% csrf_token %}
        <div class="main__header">
            <h1 class="main__title">
                {% if author.first_name %}
                    {{ author.first_name }}
                {% else %}
                    {{ author.username }}
                {% endif %}
            </h1>
            {% include "tags.html" with url=request.path food_time=food_time %}
        </div>
        {% if not request.user == author %}
            {% if author|is_following:user %}
            <div class="author-subscribe" data-author="{{author.pk}}">
                <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Отписаться от автора</button></p>
            </div>
            {% else %}
            <div class="author-subscribe" data-author="{{author.pk}}">
                <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
            </div>
            {% endif %}
        {% endif %}
        <div class="card-list" >
        {% for recipe in page %}
            {% include "recipe_item.html" with recipe=recipe %}
        {% endfor %}
    </div>
    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
  <script src="{% static '/js/components/MainCards.js' %}"></script>

  <script src="{% static '/js/components/Purchases.js' %}"></script>
  <script src="{% static '/js/components/Favorites.js' %}"></script>
  <script src="{% static '/js/components/Subscribe.js' %}"></script>

  <script src="{% static '/js/config/config.js' %}"></script>
  <script src="{% static '/js/components/AuthorRecipe.js' %}"></script>
  <script src="{% static '/js/components/Header.js' %}"></script>

  <script src="{% static '/js/api/Api.js' %}"></script>
  <script src="{% static 'authorRecipe.js' %}"></script>
{% endblock %}

receipe/templates/recipe_item.html
{% load user_filters %}
<div class="card" data-id="{{ recipe.pk }}">
    {% load thumbnail %}
    {% thumbnail recipe.image "1920x1080" crop="center" upscale=True as im %}
    <a href="{% url 'recipe_view' recipe.author.username recipe.id %}" class="link" target="_blank"><img src="{{ im.url }}" alt="Какой-то текст" class="card__image"></a>
    {% endthumbnail %}
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipe_view' recipe.author.username recipe.id %}" target="_blank">{{ recipe.title }}</a>
        <ul class="card__items">
            {% if recipe.lunch %}
            <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
            {% endif %}
            {% if recipe.breakfast %}
            <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
            {% endif %}
            {% if recipe.dinner %}
            <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
            {% endif %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' recipe.author %}" style="color: black">
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            </a></p>
        </div>
    </div>
    <div class="card__footer">
        {% if user.is_authenticated %}
            {% if recipe|is_purchase:user %}
                <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен </button>
            {% else %}
                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span> Добавить в покупки </button>
            {% endif %}
            {% if recipe|is_favourite:user %}
                <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
            {% else %}
                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
            {% endif %}
        {% endif %}
    </div>
</div>

receipe/templates/recipeform.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %}{% if change %}Редактировать{% else %}Создание рецепта{% endif %}{% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static '/pages/form.css' %}">
{% endblock %}
{% block nav %}
    {% include 'nav.html' with add_recipe=True %}
{% endblock %}
{% block content %}
    <div class="main__header">
        <h1 class="main__title">{% if change %}Редактировать{% else %}Создание рецепта{% endif %}</h1>
    </div>
    <div class="form-container">
        <form class="form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input" }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            {{ form.breakfast|addclass:"tags__checkbox tags__checkbox_style_green" }}
                            <label for="id_breakfast" class="tags__label">Завтрак</label>
                         </div>
                         <div class="tags__item">
                            {{ form.lunch|addclass:"tags__checkbox tags__checkbox_style_orange" }}
                            <label for="id_lunch" class="tags__label">Обед</label>
                         </div>
                         <div class="tags__item">
                            {{ form.dinner|addclass:"tags__checkbox tags__checkbox_style_purple" }}
                            <label for="id_dinner" class="tags__label">Ужин</label>
                         </div>
                    </div>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                        {% for in in ingr %}
                            <div class="form__field-item-ingredient" id="{{ in.pk }}">
                                <span>{{ in.ingredient.title }} {{ in.amount }}{{ in.ingredient.dimension }}</span>
                                <span class="form__field-item-delete" ></span>
                                <input id="nameIngredient_{{ in.pk }}" name="nameIngredient_{{ in }}" type="hidden" value="{{ in.ingredient.title }}">
                                <input id="valueIngredient_{{ in.pk }}" name="valueIngredient_{{ in }}" type="hidden" value="{{ in.amount }}">
                                <input id="unitsIngredient_{{ in.pk }}" name="unitsIngredient_{{ in }}" type="hidden" value="{{ in.ingredient.dimension }}">
                            </div>
                        {% endfor %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    {% for error in form.errors %}
                    <span class="form__error">
                        {{ error }}
                    </span>
                    {% endfor %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.cooking_time|addclass:"form__input" }}
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.descriptions|addclass:"form__textarea" }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {{ form.image }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__footer">
                <button type="submit" class="button button_style_blue">{% if change %}Сохранить{% else %}Создать рецепт{% endif %}</button>
                {% if change %}
                    <a style="margin-left: 2.5em" href="{% url 'recipe_delete' recipe.author.username recipe.pk %}" class="form__ingredient-link">Удалить</a>
                {% endif %}
            </div>
        </form>
    </div>
<script src="{% static '/js/config/config.js' %}"></script>
<script src="{% static '/js/components/Header.js' %}"></script>
<script src="{% static '/js/utils/debouncing.js' %}"></script>
<script src="{% static '/js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}